openapi: 3.0.3

info:
  title: Artshop
  description: Artshop backend OpenApi documentation
  version: 1.0.0

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

tags:
  - name: Register
    description: New user registration
  - name: Login
    description: User login
  - name: Users
    description: User profile
  - name: NewsLetter
    description: Subscribe to newsletter notifications
  - name: Products
    description: Available products
  - name: Orders
    description: Orders
  - name: Purchases
    description: Purchases
  - name: Admin
    description: Admin

paths:
  /api/register:
    $ref: "./resources/register.yaml"
  /api/login:
    $ref: "./resources/login.yaml"
  /api/users:
    $ref: "./resources/users.yaml"
  /api/newsletter:
    $ref: "./resources/newsletter.yaml"
  /api/products:
    $ref: "./resources/products.yaml"
  /api/products/{productId}:
    $ref: "./resources/product.yaml"
  /api/orders/{userId}:
    $ref: "./resources/orders.yaml"
  /api/orders:
    $ref: "./resources/deleteAllOrders.yaml"
  /api/orders/{orderId}:
    $ref: "./resources/removeItem.yaml"
  /api/purchases/{userId}:
    $ref: "./resources/purchases.yaml"
  /api/admin/addproducts:
    $ref: "./resources/addproducts.yaml"
  /api/admin/products/{id}:
    $ref: "./resources/removeproduct.yaml"
  /api/admin/editproducts/{id}:
    $ref: "./resources/editproduct.yaml"

components:
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT 