get:
  summary: Get available products
  tags: [Products]
  responses:
    200:
      description: List of available products
      content:
        application/json:
          schema:
            $ref: '../schemas/Products.yaml'
    500:
      $ref: '../responses/ServerError.yaml' 