get:
  summary: Find product by ID
  tags: [Products]
  parameters:
    - in: path
      name: productId
      schema:
        type: string
      required: true
      description: ID of the product
  security:
    - bearerAuth: []
  responses:
    200:
      description: Selected product details
      content:
        application/json:
          schema:
            $ref: '../schemas/Products.yaml'
    400:
      $ref: '../responses/ValidationError.yaml'
    500:
      $ref: '../responses/ServerError.yaml' 